"""Custom interfaces for conversation storage."""

from __future__ import annotations

from typing import Protocol

from .models import ChatSession, Message, User


class ConversationStore(Protocol):
    def create_user(self, user: User) -> User: ...

    def get_user(self, user_id: str) -> User | None: ...

    def find_user_by_username(self, username: str) -> User | None: ...

    def list_users(self) -> list[User]: ...

    def delete_user(self, user_id: str, cascade: bool = False) -> dict[str, int]: ...

    def create_session(self, session: ChatSession) -> ChatSession: ...

    def get_session(self, session_id: str) -> ChatSession | None: ...

    def update_session(self, session: ChatSession) -> ChatSession: ...

    def list_sessions(self, user_id: str | None = None) -> list[ChatSession]: ...

    def delete_session(self, session_id: str) -> dict[str, int]: ...

    def append_message(self, message: Message) -> Message: ...

    def list_messages(self, session_id: str) -> list[Message]: ...

    def delete_all(self) -> dict[str, int]: ...
